runtime: nodejs10
api_version: 1
## threadsafe: true

handlers:

- url: /(.+\.php)$
  script: \1

- url: /.*
  script: index.php
  
  secure: always

env_variables:
  ## Put production environment variables here.
  ## APP_KEY: base64:kVxyWJddmceGVCg36t68XOJs9YyhVcZ01Y9jUz2C68U=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  ## Google App engine only allows writing to tmp
  APP_SERVICES_CACHE: /tmp/services.php
  APP_PACKAGES_CACHE: /tmp/packages.php
  APP_CONFIG_CACHE: /tmp/config.php
  APP_ROUTES_CACHE: /tmp/routes.php

  SESSION_DRIVER: cookie
